DROP DATABASE IF EXISTS taskr;
CREATE DATABASE taskr; 

\c taskr

DROP TABLE IF EXISTS todos;
CREATE TABLE todos (
id SERIAL PRIMARY KEY,
task VARCHAR(80) NOT NULL,
isCompleted BOOLEAN DEFAULT FALSE
);